# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from proto import stresmg_pb2 as proto_dot_stresmg__pb2


class uploadServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetFile = channel.unary_unary(
        '/filetransfer.uploadService/GetFile',
        request_serializer=proto_dot_stresmg__pb2.FileRequest.SerializeToString,
        response_deserializer=proto_dot_stresmg__pb2.FileResponse.FromString,
        )
    self.GetFiles = channel.unary_unary(
        '/filetransfer.uploadService/GetFiles',
        request_serializer=proto_dot_stresmg__pb2.FilesRequest.SerializeToString,
        response_deserializer=proto_dot_stresmg__pb2.FilesResponse.FromString,
        )


class uploadServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetFile(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetFiles(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_uploadServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetFile': grpc.unary_unary_rpc_method_handler(
          servicer.GetFile,
          request_deserializer=proto_dot_stresmg__pb2.FileRequest.FromString,
          response_serializer=proto_dot_stresmg__pb2.FileResponse.SerializeToString,
      ),
      'GetFiles': grpc.unary_unary_rpc_method_handler(
          servicer.GetFiles,
          request_deserializer=proto_dot_stresmg__pb2.FilesRequest.FromString,
          response_serializer=proto_dot_stresmg__pb2.FilesResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'filetransfer.uploadService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
