# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/stresmg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/stresmg.proto',
  package='filetransfer',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13proto/stresmg.proto\x12\x0c\x66iletransfer\"\x1f\n\x0b\x46ileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"\x1c\n\x0c\x46ileResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x1c\n\x0c\x46ilesRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\x1d\n\rFilesResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2\x9a\x01\n\ruploadService\x12\x42\n\x07GetFile\x12\x19.filetransfer.FileRequest\x1a\x1a.filetransfer.FileResponse\"\x00\x12\x45\n\x08GetFiles\x12\x1a.filetransfer.FilesRequest\x1a\x1b.filetransfer.FilesResponse\"\x00\x62\x06proto3')
)




_FILEREQUEST = _descriptor.Descriptor(
  name='FileRequest',
  full_name='filetransfer.FileRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filename', full_name='filetransfer.FileRequest.filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=68,
)


_FILERESPONSE = _descriptor.Descriptor(
  name='FileResponse',
  full_name='filetransfer.FileResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='filetransfer.FileResponse.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=98,
)


_FILESREQUEST = _descriptor.Descriptor(
  name='FilesRequest',
  full_name='filetransfer.FilesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='filetransfer.FilesRequest.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=128,
)


_FILESRESPONSE = _descriptor.Descriptor(
  name='FilesResponse',
  full_name='filetransfer.FilesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='filetransfer.FilesResponse.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=159,
)

DESCRIPTOR.message_types_by_name['FileRequest'] = _FILEREQUEST
DESCRIPTOR.message_types_by_name['FileResponse'] = _FILERESPONSE
DESCRIPTOR.message_types_by_name['FilesRequest'] = _FILESREQUEST
DESCRIPTOR.message_types_by_name['FilesResponse'] = _FILESRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FileRequest = _reflection.GeneratedProtocolMessageType('FileRequest', (_message.Message,), {
  'DESCRIPTOR' : _FILEREQUEST,
  '__module__' : 'proto.stresmg_pb2'
  # @@protoc_insertion_point(class_scope:filetransfer.FileRequest)
  })
_sym_db.RegisterMessage(FileRequest)

FileResponse = _reflection.GeneratedProtocolMessageType('FileResponse', (_message.Message,), {
  'DESCRIPTOR' : _FILERESPONSE,
  '__module__' : 'proto.stresmg_pb2'
  # @@protoc_insertion_point(class_scope:filetransfer.FileResponse)
  })
_sym_db.RegisterMessage(FileResponse)

FilesRequest = _reflection.GeneratedProtocolMessageType('FilesRequest', (_message.Message,), {
  'DESCRIPTOR' : _FILESREQUEST,
  '__module__' : 'proto.stresmg_pb2'
  # @@protoc_insertion_point(class_scope:filetransfer.FilesRequest)
  })
_sym_db.RegisterMessage(FilesRequest)

FilesResponse = _reflection.GeneratedProtocolMessageType('FilesResponse', (_message.Message,), {
  'DESCRIPTOR' : _FILESRESPONSE,
  '__module__' : 'proto.stresmg_pb2'
  # @@protoc_insertion_point(class_scope:filetransfer.FilesResponse)
  })
_sym_db.RegisterMessage(FilesResponse)



_UPLOADSERVICE = _descriptor.ServiceDescriptor(
  name='uploadService',
  full_name='filetransfer.uploadService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=162,
  serialized_end=316,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetFile',
    full_name='filetransfer.uploadService.GetFile',
    index=0,
    containing_service=None,
    input_type=_FILEREQUEST,
    output_type=_FILERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetFiles',
    full_name='filetransfer.uploadService.GetFiles',
    index=1,
    containing_service=None,
    input_type=_FILESREQUEST,
    output_type=_FILESRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_UPLOADSERVICE)

DESCRIPTOR.services_by_name['uploadService'] = _UPLOADSERVICE

# @@protoc_insertion_point(module_scope)
